### ISSUE TITLE
额，出了个问题。。。

### ISSUE THREAD

**Issue by xw-yin** [LoeiFy/Diaspora#42]
yinxinwang.top/:1 Access to Image at 'http://52.197.228.14/wp-content/uploads/2016/11/saber.jpg' from origin 'http://yinxinwang.top' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://yinxinwang.top' is therefore not allowed access.
Diaspora.js:666  Github  https://github.com/LoeiFy/Diaspora
plugin.js:25 The deviceorientation event is deprecated on insecure origins, and support will be removed in the future. You should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.
h.enable @ plugin.js:25
plugin.js:77 Uncaught DOMException: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The HTMLImageElement provided is in the 'broken' state.
    at new b (http://52.197.228.14/wp-content/themes/Diaspora-master/static/plugin.js:77:205)
    at new b (http://52.197.228.14/wp-content/themes/Diaspora-master/static/plugin.js:68:76)
    at HTMLImageElement.<anonymous> (http://52.197.228.14/wp-content/themes/Diaspora-master/assets/Diaspora.js:298:27)
    at HTMLImageElement.dispatch (http://52.197.228.14/wp-content/themes/Diaspora-master/static/jquery.min.js:3:4663)
    at HTMLImageElement.i (http://52.197.228.14/wp-content/themes/Diaspora-master/static/jquery.min.js:3:628)
    at Object.trigger (http://52.197.228.14/wp-content/themes/Diaspora-master/static/jquery.min.js:3:3348)
    at HTMLImageElement.<anonymous> (http://52.197.228.14/wp-content/themes/Diaspora-master/static/jquery.min.js:3:10834)
    at Function.each (http://52.197.228.14/wp-content/themes/Diaspora-master/static/jquery.min.js:2:11819)
    at init.each (http://52.197.228.14/wp-content/themes/Diaspora-master/static/jquery.min.js:2:8381)
    at init.trigger (http://52.197.228.14/wp-content/themes/Diaspora-master/static/jquery.min.js:3:10810)

**Comment by LoeiFy** [comment]
@yxw940521 设置图片地址 `http://52.197.228.14/wp-content/themes/Diaspora-master/images/default.jpg` 的服务器 `52.197.228.14` 允许跨域

**Comment by xw-yin** [comment]
嗯嗯 搞定了，多谢
